### ISSUE TITLE
Ambiguous method error when calling GetVortoValue with 1.4 package

### ISSUE THREAD

**Issue by joshua-stewart** [mattbrailsford/Vorto#10]
I just installed the most recent 1.4 package and I am getting the following error:

CS0121: The call is ambiguous between the following methods or properties: 'Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.GetVortoValue(Umbraco.Core.Models.IPublishedContent, string, string, bool, object)' and 'Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.GetVortoValue(Umbraco.Core.Models.IPublishedContent, string, string, string, bool, object)'

I am running Umbraco 7.1.9.

Also, if I force the method by calling @Model.Content.GetVortoValue("vortoTitle"), null, null, false, null) I get the dreaded Object reference not set to an instance of an object that was detailed here - https://our.umbraco.org/projects/backoffice-extensions/vorto/bugs-feedback-suggestions/55572-Strange-GetVortoValue%28%29-nullreference-Exception?p=0
.

**Comment by mattbrailsford** [comment]
Hi Joshua,

Looks like I was a bit eager to add some extra extension methods without fully testing backwards compatibility. I've just rolled them back for now while I test them out, so if you want to try v1.4.1 it should work.

Many thanks

Matt

**Comment by joshua-stewart** [comment]
Thanks, Matt. Appreciate the quick turn around. The ambiguous error is fixed, but I am still getting the error below when calling GetVortoValue. I've been fighting with it for a few hours and I can't seem to get it to work under my install of 7.1.9.

Object reference not set to an instance of an object.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error:
Line 7:    <head>
Line 8:      <meta charset="utf-8">
Line 9:      <title>@Model.Content.GetVortoValue("vortoTitle") </title>
Line 10:     <meta name="description" content="@Umbraco.Field("metaDescription")">


Source File: c:\inetpub\wwwroot\xxxxxx\Views\umbLayout.cshtml    Line: 9

Stack Trace:

[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Core.Models.PublishedContent.<>c__DisplayClass12.<GetCompatConverters>b__f(IPropertyEditorValueConverter x) +55
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +5919277
   System.Linq.<UnionIterator>d__88`1.MoveNext() +823
   System.Linq.WhereEnumerableIterator`1.MoveNext() +195
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +487
   System.Linq.Enumerable.ToArray(IEnumerable`1 source) +102
   Umbraco.Core.Models.PublishedContent.PublishedPropertyType.InitializeConverters() +216
   Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.CreateDummyPropertyType(Int32 dataTypeId, String propertyEditorAlias) +218
   Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.GetVortoValue(IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, T defaultValue) +1127
   Our.Umbraco.Vorto.Extensions.IPublishedContentExtensions.GetVortoValue(IPublishedContent content, String propertyAlias, String cultureName, Boolean recursive, Object defaultValue) +100
   ASP._Page_Views_umbLayout_cshtml.Execute() in c:\inetpub\wwwroot\9mtc.com\Views\umbLayout.cshtml:9
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +279
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +124
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +195
   System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body) +207
   System.Web.WebPages.WebPageBase.PopContext() +191
   Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer) +139
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +379
   System.Web.Mvc.<>c__DisplayClass1a.<InvokeActionResultWithFilters>b__17() +32
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation) +613
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilter(IResultFilter filter, ResultExecutingContext preContext, Func`1 continuation) +613
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +263
   System.Web.Mvc.Async.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult) +240
   System.Web.Mvc.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult) +28
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +15
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +15
   System.Web.Mvc.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +15
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +606
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288

**Comment by mattbrailsford** [comment]
Hi Joshua,

Just pushed another update. Do you want to try that one?

Many thanks

Matt

**Comment by joshua-stewart** [comment]
It works like a charm now. Thanks so much Matt. I really appreciate you getting this fixed so quickly. Developers like you are the reason I love Umbraco so much. Have a great weekend.

**Comment by mattbrailsford** [comment]
Awesome. No problem. Thanks for reporting the issue. Have a good one.
