### ISSUE TITLE
getVortoValue not working

### ISSUE THREAD

**Issue by alainvanderbroeck** [mattbrailsford/Vorto#14]
Hi Matt,

I was wondering if you can help me out.

- I installed the Vorto package for Umbraco 7.1.
- I wrapped up the datatype "USN Small Richtext editor"
- I selected the new datatype at the document type for the field "page summary"
- Then, when editing the page, i can see and fill out the wrapped element
so far, so good

Your documentation tells: "To retrieve the values, Vorto comes with a few handy IPublishedContent extension methods (sorry, no dynamics support yet) namly HasVortoValue and GetVortoValue. These can be used as direct replacements to the built in HasValue and GetPropertyValue methods that come with Umbraco (if the value you are after isn't a Vorto value, it defaults back to the Umbraco implementation)."

As the page summary is shown in my subpage listing, i opened the file "USN_SubPageLisiting" and tried a couple of things to get the votro text for my current language. But everything i do doesn't work.
When i do nothing at all my page shows "Our.Umbraco.Vorto.Models.VortoValue" in place of the value.

I am not a .NET programmer and no Umbraco specialist.
Could you please tell me what to do, to make this work?

See my screenshots below of my current code

![image](https://cloud.githubusercontent.com/assets/4488022/8431111/70cfb57c-1f37-11e5-8c7f-cd452faef605.png)

![image](https://cloud.githubusercontent.com/assets/4488022/8431120/902569a8-1f37-11e5-969b-879d570e6c28.png)

**Comment by mattbrailsford** [comment]
Hi @alainvanderbroeck 

Have you assigned a culture to your homepage node so that Vorto knows which language value to lookup? Have you tried calling item.GetVortoValue("pageSummary", "culture") where "culture" is the culture value you have set a value for (just to make sure retrieving a value works)?

Many thanks

Matt

**Comment by alainvanderbroeck** [comment]
Hi @mattbrailsford 

I checked both things

1. My homepage has a culture assigned. As you can see in the screenshot below.
![image](https://cloud.githubusercontent.com/assets/4488022/8431709/a9acecb2-1f3b-11e5-8c4f-baaca2449bf5.png)

2. When i call item.GetVortoValue("pageSummary", "nl")
i get the following error:
Compiler Error Message: CS1061: 'Umbraco.Core.Models.IPublishedContent' does not contain a definition for 'GetVortoValue' and no extension method 'GetVortoValue' accepting a first argument of type 'Umbraco.Core.Models.IPublishedContent' could be found (are you missing a using directive or an assembly reference?)
As you can see in the screenshot(s) below:

![image](https://cloud.githubusercontent.com/assets/4488022/8431733/c7f3cbf0-1f3b-11e5-8e9b-adaebf1f9750.png)

![image](https://cloud.githubusercontent.com/assets/4488022/8431742/d51f4eb2-1f3b-11e5-8c34-58e14ced55f6.png)

**Comment by JBoye** [comment]
Hi @alainvanderbroeck 

Try adding this line to the top of your cshtml file:

@using Our.Umbraco.Vorto.Extensions;

**Comment by alainvanderbroeck** [comment]
Yes! That did the trick!

Thank you very much!

**Comment by mattbrailsford** [comment]
thanks @JBoye I really should have thought of that myself :)

@alainvanderbroeck glad you got it working.
