### ISSUE TITLE
Cookie set path to '/'

### ISSUE THREAD

**Issue by Kimtho** [mattbrailsford/Vorto#16]
We need to set the path to '/' so the cookie wont be set at '/umbraco/'

**Comment by mattbrailsford** [comment]
Unfortunately the angular js $cookies service doesn't let you set the path, however I have recently changed this to use localStorage anyway with a fallback to cookies. I realiase this might still pose a problem for people with older browsers, but give Umbraco 7 only supports newer browsers which should support local storage, I think this is a reasonable solution.
