### ISSUE TITLE
Is it support RTL language?

### ISSUE THREAD

**Issue by Toryalai** [mattbrailsford/Vorto#22]
Hi Matt,

Thanks for the great project.

is it support Right to left (RTL) language?

**Comment by mattbrailsford** [comment]
There is a PR for adding this, however from testing, there are issues with compatability of property editors themselves supporting RTL so it's a bit hit and miss. Feel free to test the PR and let me know if it solves your issue.

**Comment by Toryalai** [comment]
Thanks from your response, I am so sorry, I am very new in umbraco, I don't know how to test the PR,
My problem is that, when I change language in drop down list from English to our local language (Pashto or Dari), the whole web site layout must be changed from LTR to RTL, but it's not.
Thanks.
