### ISSUE TITLE
Unable to select multiple nodes when using a multi-node tree picker

### ISSUE THREAD

**Issue by samgooch** [mattbrailsford/Vorto#7]
I am unable to select multiple nodes when using a Vorto-wrapped multi-node tree picker.

The dialog buttons for 'Cancel' and 'Select' are not displayed in the bottom right handside.

Thanks,
Sam

**Comment by mattbrailsford** [comment]
Dunno if any recent changes have fixed this, but just run a test with MNTP inside a vorto field and it worked so going to close this issue. If you can provide more information I'll be happy to reopen this issue.
