### ISSUE TITLE
Update property extended from Vorto in code behind

### ISSUE THREAD

**Issue by paulocampos** [mattbrailsford/Vorto#9]
Hi guys.

I can update a property of my content type using code behind and then save the value in each language ?

If so, how can I do?
thank you

Paulo

**Comment by anth12** [comment]
Content Properties using the Vorto data type use the below json format:
```
{  
   "values":{  
      "en-US":"en-US content here",
      "es-ES":"es-ES contenidos aquí"
   },
   "dtdGuid":"34d1bc40-8cdc-4437-bb62-d0780ecf857a"
}
```

You can use the standard Umbraco API to retrieve Content, update a property & save as required:
```
var content = ApplicationContext.Current.Services.ContentService.GetById(contentId);
var vortoPropertyValue = content.GetValue("myVortoProperty");
    
// TODO: Modify 'vortoPropertyValue' as you like

content.SetValue("myVortoProperty", vortoPropertyValue);
```

You can then parse the json string to a model similar to [VortoValue](https://github.com/mattbrailsford/Vorto/blob/master/Src/Our.Umbraco.Vorto/Models/VortoValue.cs) (`VortoValue` is internal so you will need to recreate locally).

```
var propertyValue = JsonConvert.DeserializeObject<VortoValue>(vortoPropertyValue);
propertyValue.Values["en-EN"] = "new value";
vortoPropertyValue = JsonConvert.SerializeObject(propertyValue);
```

**Comment by stefchri** [comment]
For the creation of new content I fixed it by doing the following:

```
private Guid GetDataTypeDefinitionGuid(Property property)
        {
            var dtdId = property.PropertyType.DataTypeDefinitionId;
            var dtd = Services.DataTypeService.GetDataTypeDefinitionById(dtdId);
            return dtd.Key;
        }

        public Property SetVortoProperty(Property property, string value)
        {
            var id = GetDataTypeDefinitionGuid(property);

            var vortoValue = new VortoValue();
            vortoValue.DtdGuid = id;
            vortoValue.Values = new Dictionary<string, object>();
            vortoValue.Values.Add("nl-BE", value);
            property.Value = JsonConvert.SerializeObject(vortoValue);
            return property;
        }
```

**Comment by ryanmcdonough** [comment]
@stefchri I just tried to use this code in a project and I'm getting: 

Error	CS1729	'VortoValue' does not contain a constructor that takes 0 arguments	randomfile.cs	

Has this changed, or did you do more?

**Comment by stefchri** [comment]
Hi Ryan, I changed the source code of umbraco-vorto to make the vortovalue
constructor public.

**Comment by rasmuseeg** [comment]
#73
